mall/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ProductList.as_view()),
    path('<int:pk>/', views.ProductDetail.as_view()),
    path('category/<str:slug>', views.category_page),
    path('create_product/', views.ProductCreate.as_view()),
    path('update_product/<int:pk>/', views.ProductUpdate.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('search/<str:q>/', views.ProductSearch.as_view()),
    path('cart/<int:pk>', views.cart, name="cart"),
]

sweetvirus/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mall/', include('mall.urls')),
    path('', include('single_pages.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #서버IP/media/

mall/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/mall/category/{self.slug}'

    class Meta:
        verbose_name_plural = 'Categories'


class Brand(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    address = models.CharField(max_length=100)
    contact = models.CharField(max_length=50)
    since = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=30)
    info_text = MarkdownxField()
    img = models.ImageField(upload_to='mall/images/%Y/%m/%d/', blank=True)
    price = models.CharField(max_length=10)
    brand = models.ForeignKey(Brand, null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    calories = models.CharField(max_length=10)
    gram = models.CharField(max_length=10)
    nutrition_img = models.ImageField(upload_to='mall/images/%Y/%m/%d/', blank=True)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'[{self.pk}]{self.name} ({self.price}원)'

    def get_absolute_url(self):
        return f'/mall/{self.pk}/'

    def get_content_markdown(self):
        return markdown(self.info_text)

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()

        else:
            return 'https://doitdjango.com/avatar/id/475/21399d185a8ff82e/svg/{self.author.email}/'


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.product.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()

        else:
            return 'https://doitdjango.com/avatar/id/475/21399d185a8ff82e/svg/{self.author.email}/'


class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.author}::{self.product.name}'

mall/forms.py
from .models import Comment, Cart
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        labels = {
            'content' : '댓글',
        }


class CartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = ('product',)

mall/views.py
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, Category
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import CommentForm, CartForm


class ProductList(ListView):
    model = Product
    ordering = '-pk'
    paginate_by = 8

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_product_count'] = Product.objects.filter(category=None).count()
        return context


class ProductDetail(DetailView):
    model = Product

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_product_count'] = Product.objects.filter(category=None).count()
        context['comment_form'] = CommentForm
        return context


def category_page(request, slug):
    if slug == 'no_category':
        category = '기타'
        product_list = Product.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        product_list = Product.objects.filter(category=category)

    return render(request,
                  'mall/product_list.html',
                  {
                      'product_list': product_list,
                      'categories': Category.objects.all(),
                      'no_category_product_count': Product.objects.filter(category=None).count(),
                      'category': category
                  }
                  )


class ProductCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Product
    fields = ['name', 'info_text', 'img', 'price', 'brand', 'category', 'calories', 'gram', 'nutrition_img']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user
            response = super(ProductCreate, self).form_valid(form)
            return response
        else:
            return redirect('/mall/')


class ProductUpdate(LoginRequiredMixin, UpdateView):
    model = Product
    fields = ['name', 'info_text', 'img', 'price', 'brand', 'category', 'calories', 'gram', 'nutrition_img']

    template_name = 'mall/product_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(ProductUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductUpdate, self).get_context_data()
        return context

    def form_valid(self, form):
        response = super(ProductUpdate, self).form_valid(form)
        return response


def new_comment(request, pk):
    if request.user.is_authenticated:
        product = get_object_or_404(Product, pk=pk)

        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.product = product
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())

        else:
            return redirect(product.get_absolute_url())
    else:
        raise PermissionDenied


def cart(request, pk):
    if request.user.is_authenticated:
        product = get_object_or_404(Product, pk=pk)

        form = CartForm().save(commit=False)
        form.author = request.user
        form.product = product
        form.save()
        return redirect(product.get_absolute_url())

    else:
        return redirect('mall')


class ProductSearch(ProductList):
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        product_list = Product.objects.filter(
            Q(name__contains=q) | Q(brand__name__contains=q)
        ).distinct()
        return product_list

    def get_context_data(self, **kwargs):
        context = super(ProductSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'검색어 <{q}>에 대한 {self.get_queryset().count()}개의 상품이 있습니다.'
        return context

mall/templates/mall/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title_area %} Sweet Virus {% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{%static 'mall/assets/cookie_bite.png'%}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'mall/css/styles.css'%}" rel="stylesheet" />
        <link href="{% static 'mall/bootstrap/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen">
        <script src="https://kit.fontawesome.com/882b461dc1.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    </head>

    <body>

    {% include 'mall/navbar.html' %}

            {% block main_area %}
            {% endblock %}

    {% include 'mall/footer.html' %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

    </body>
</html>

mall/templates/mall/base_full.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Shop Homepage</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{%static 'mall/assets/favicon.ico'%}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'mall/css/styles.css'%}" rel="stylesheet" />
        <script src="https://kit.fontawesome.com/882b461dc1.js" crossorigin="anonymous"></script>
    </head>

    <body>

    {% include 'mall/navbar.html' %}

            {% block main_area %}
            {% endblock %}

<div class="fixed-bottom">
 {% include 'mall/footer.html' %}
</div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

    </body>
</html>

mall/templates/mall/footer.html
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">
            서울특별시 도봉구 삼양로 144길 33<br>
            010-9911-****<br><br>
            Copyright &copy; Duksung Internet Programming 2021
        </p>
    </div>
</footer>

mall/templates/mall/navbar.html
{% load socialaccount %}
<script src="https://kit.fontawesome.com/882b461dc1.js" crossorigin="anonymous"></script>
<!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="/">Sweet Virus</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="/mall/">Product</a></li>
                        <li class="nav-item"><a class="nav-link" href="/about_us/">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="/mypage/">MyPage</a></li>
                    </ul>

                    <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    {% if user.socialaccount_set.all.0.get_avatar_url %}
                                    <img class="rounded-circle" width="25px" src="{{user.socialaccount_set.all.0.get_avatar_url}}">
                                    {% else %}
                                    <img class="rounded-circle" width="25px" src='https://doitdjango.com/avatar/id/475/21399d185a8ff82e/svg/{{user.email}}/'>
                                    {% endif %}
                                    &nbsp;{{ user.username }}
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="text-align:center;">
                                    <a role="button" class="btn btn btn-secondary" href="/accounts/logout/">
                                        Log out
                                    </a>
                                </div>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a role="button" class="nav-link btn btn-outline-secondary" href="#" data-toggle="modal" data-target="#loginModal">Log In</a>
                            </li>
                        {% endif %}
                    </ul>


<!--                    <form class="d-flex">-->
<!--                        <button class="btn btn-outline-dark" type="submit">-->
<!--                            <i class="bi-cart-fill me-1"></i>-->
<!--                            Cart-->
<!--                            <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>-->
<!--                        </button>-->
<!--                    </form>-->
                </div>
            </div>
        </nav>



    <!-- Modal -->
    <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginModalLabel"><i class="fas fa-sign-in-alt"></i> &nbsp;Log In</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="{% provider_login_url 'google' %}"><i class="fab fa-google"></i> &nbsp; Log in with Google</a>
                            <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/login/"><i class="far fa-envelope"></i> &nbsp; Log in with E-mail</a>
                        </div>
                        <div class="col-md-6">
                            <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/signup/"><i class="far fa-envelope"></i> &nbsp; Sign Up with E-mail</a>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

mall/templates/mall/product_detail.html
{% extends 'mall/base.html' %}
{% load crispy_forms_tags %}

{% block title_area %}Product - {{product.name}}{% endblock %}

{% block main_area %}
{% include 'mall/side.html' %}
        <!-- Product section-->
        <section class="pt-2 pb-5">
            <div class="container px-4 px-lg-5 my-3">
                <div class="row gx-4 gx-lg-5 py-3 align-items-center">

                    <div class="col-md-6">
                        {% if product.img %}
                            <img class="card-img-top mb-5 mb-md-0" src="{{ product.img.url }}" alt="{{product.name}}의 이미지" />
                        {% else %}
                            <img class="card-img-top mb-5 mb-md-0" src="https://dummyimage.com/600x700/dee2e6/6c757d.jpg" alt="..." />
                        {% endif %}
                    </div>

                    <div class="col-md-6">
                        <div class="mb-3">
                        {% if product.category %}
                            <span class="badge badge-pill badge-info">{{ product.category }}</span>
                        {% else %}
                            <span class="badge badge-pill badge-info">기타</span>
                        {% endif %}
                        {% if product.brand %}
                             <span class="badge badge-pill badge-success">{{ product.brand }}</span>
                        {% else %}
                             <span class="badge badge-pill badge-success">기타</span>
                            {% endif %}
                        </div>

                        <h2 class="display-8 fw-bolder">{{ product.name }}</h2><br>

                        <div class="fs-5 mb-5">
                            <span >
                                가격&nbsp;&nbsp;&nbsp; : &nbsp; {{ product.price }}원<br>
                                용량&nbsp;&nbsp;&nbsp; : &nbsp; {{product.gram}}g<br>
                                칼로리 : &nbsp; {{ product.calories }}kcal<br>
                            </span>
                        </div>

                        <p class="lead">{{ product.get_content_markdown | safe }}</p><br>

                        <div class="d-flex">
                            {% if user.is_authenticated %}
                            <a href="{% url 'cart' product.pk %}">
                                <button class="btn btn-outline-secondary flex-shrink-0" type="submit">
                                    <i class="bi-cart-fill me-1"></i>
                                    장바구니
                                </button>
                            </a>

                            {% else %}
                            <button class="btn btn-outline-dark flex-shrink-0" >
                                <i class="bi-cart-fill me-1"></i>
                                로그인 후 장바구니 기능을 이용할 수 있습니다.
                            </button>
                            {% endif %}

                        </div>

                    </div>
                </div>

                <hr>
                <div class="row">
                    <div class="col-md-6 mt-4" style="text-align:center;">
                        <h5 class="display-8 fw-bolder">[ 영양정보 ]</h5><br>
                    </div>
                    <div class="col-md-6 mt-4" style="text-align:center;">
                        <h5 class="display-8 fw-bolder">[ 제조사 ]</h5><br>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        {% if product.nutrition_img %}
                        <img class="card-img-top mb-5 mb-md-0" src="{{ product.nutrition_img.url }}" alt="{{product.name}}의 이미지" />
                        {% else %}
                        <div class="fs-5 mb-5" style="text-align:center;">
                            <span >영양성분 정보가 존재하지 않습니다.</span>
                        </div>
                        {% endif %}
                    </div>

                    <div class="col-md-6">
                        {% if product.brand %}
                        <div class="fs-5 mb-5" style="text-align:center;">
                            <span >
                                제조사명 : {{ product.brand.name }}<br>
                                주소 : {{product.brand.address}}<br>
                                연락처 : {{ product.brand.contact }}<br>
                                설립일 : {{ product.brand.since | date:"Y.m.d"}}<br>
                            </span>
                        </div>
                        {% else %}
                        <div class="fs-5 mb-5" style="text-align:center;">
                            <span >제조사 정보가 존재하지 않습니다.</span>
                        </div>
                        {% endif %}
                    </div>
                </div>

                <div class="row mt-2">
                    <div class="col-md-12" style="text-align:right">
                    {% if user.is_authenticated and user == product.author %}
                        <a href="/mall/update_product/{{product.pk}}/" class="btn btn-outline-warning btn-small float-right">
                            <i class="fas fa-pen"></i>
                            상품 수정
                        </a>
                    {% endif %}
                    </div>
                </div>

            </div>
        </section>


<!-- Comments section-->
        <section class="pt-2 pb-5">
            <div class="container px-4 px-lg-5 my-3" id="comment-area">
                <div class="card bg-light">
                    <div class="row gx-4 gx-lg-5 py-3 align-items-center card-body">
                        <!-- Comment form-->
                        {% if user.is_authenticated %}
                            <form class="mb-4" id="comment-form" method="POST" action="{{ product.get_absolute_url }}new_comment/">
                                {% csrf_token %}
                                    <div class="form-group">
                                    {{comment_form | crispy}}
                                    </div>
                                    <div class="mt-1" style="text-align: right;">
                                        <button type="submit" class="btn btn-secondary">작성</button>
                                    </div>
                            </form>
                            <div>
                                {% else %}
                                    <a role="button" class="btn btn-secondary mb-5 " href="#"
                                    data-toggle="modal" data-target="#loginModal">
                                        로그인 후 댓글을 작성할 수 있습니다. 클릭 시 로그인창으로 이동합니다.</a>
                                {% endif %}
                            </div>
                                {% if product.comment_set.exists %}
                                {% for comment in product.comment_set.all %}
                                <!-- Single comment-->
                                <div class="d-flex mb-2 " id="comment-{{comment.pk}}" >
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="{{comment.get_avatar_url}}" alt="{{comment.author}}" width="60px"/></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">{{ comment.author.username }} &nbsp;&nbsp;&nbsp;
                                            <small class="text-muted">{{ comment.created_at | date:"y.m.d H:i"}}</small>
                                        </div>
                                        <p>{{comment.content | linebreaks}}</p>
                                    </div>
                                </div>
                                {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
        </section>

{% endblock %}

mall/templates/mall/product_form.html
{% extends 'mall/base.html' %}
{% load crispy_forms_tags %}
{% block main_area %}
<div class="container mt-4 mb-5 pb-3">
    <h2>상품 등록</h2><hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form | crispy}}
        <div style="text-align: right">
            <button type="submit" class="btn btn-warning float-right">등록하기</button>
        </div>
    </form>
</div>
{{form.media}}
{% endblock %}

mall/templates/mall/product_update_form.html
{% extends 'mall/base.html' %}
{% load crispy_forms_tags %}
{% block main_area %}
<div class="container mt-4 mb-5 pb-3">
    <h2>상품 수정</h2><hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form | crispy}}
        <div style="text-align: right">
            <button type="submit" class="btn btn-warning float-right">수정하기</button>
        </div>
    </form>
</div>
{{form.media}}
{% endblock %}

mall/templates/mall/side.html
        <header class="py-3 px-5 px-lg-5">
            <div class="container" style="text-align: center;">
                <div class="row text-center text-white">

                    <!-- 카테고리 -->
                    <div class="col-8">
                        {% for c in categories %}
                        <a class="btn btn-info btn-sm" href="{{c.get_absolute_url}}"><b>{{ c }}</b> ({{ c.product_set.count }})</a>
                        {% endfor %}
                        <a class="btn btn-info btn-sm" href="http://127.0.0.1:8000/mall/category/no_category"><b>기타 </b>({{ no_category_product_count }})</a>
                    </div>

                    <!-- 검색 -->
                    <div class="col-4">
                        <div class="input-group">
                            <input class="form-control" id="search-input" type="text" placeholder="제품명 / 브랜드 검색" aria-label="Enter search term..." aria-describedby="button-search" />
                            <button class="btn btn-success" id="button-search" type="button" onclick="searchProduct()"><i class="fas fa-search"></i></button>
                        </div>
                    </div>

                </div>
            </div>
        </header>

        <script>
            function searchProduct(){
                let searchValue = document.getElementById('search-input').value.trim();
                if(searchValue.length > 1) {
                    location.href = "/mall/search/" + searchValue + "/";
                }
                else{
                    alert('검색어(' + searchValue + ')가 너무 짧습니다.');
                }
            };
            document.getElementById('search-input').addEventListener('keyup',
                function(event) {
                    if(event.key == 'Enter') {searchProduct();}
                }
            )
        </script>